### ISSUE TITLE
track.getCapabilities not supported in Firefox

### ISSUE THREAD

**Issue by stuartlangridge** [NielsLeenheer/WebcamBarcodeScanner#1]
https://point-of-sale.dev/ says that @point-of-sale/[webcam-barcode-scanner](https://github.com/NielsLeenheer/WebcamBarcodeScanner) is supported in Firefox, but in https://github.com/NielsLeenheer/WebcamBarcodeScanner/blob/2795ed4dbcdb54f5f37da721a75e13f5818bc727/src/main.js#L102 it calls `track.getCapabilities()`, which [Firefox sadly does not support](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities#browser_compatibility). (Maybe it should detect support and skip the capabilities check if not?)

**Comment by NielsLeenheer** [comment]
Fixed...

Btw, it was great chatting with you after Sotb a couple of week ago.

**Comment by stuartlangridge** [comment]
> Fixed...
> 
> 
> 
> Btw, it was great chatting with you after Sotb a couple of week ago. 

Yay!

I'm now looking for an excuse to use this library :-)
